---
- hosts: localhost
  become: true
  vars:
    aws_region: us-east-1
    posgres_instance: db.t2.micro
    bucket_name: oghenerobuck
    pkgs:
    - boto
    - boto3
    - awscli


  tasks:
  - name: Installing neccessary packages
    pip:
      name: "{{ pkgs }}"
      state: latest

  - name: Create an empty bucket
    aws_s3:
      bucket: "{{ bucket_name }}"
      mode: create
      permission: public-read

  - name: Basic rds postgresql database provisioning
    rds:
      command: create
      instance_name: oghenero-database
      db_engine: postgres
      size: '10'
      instance_type: "{{ posgres_instance }}"
      username: postgres_admin
      password: 1nsecure
      region: "{{ aws_region }}"
      tags:
        Environment: testing
        Application: verint-oghenero

  - name: Creating table in DynamoDB
    command: >
      aws dynamodb create-table \
      --table-name Music \
      --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S \
      --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE \
      --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 \
      --region "{{ aws_region }}" \
      --tags Key=Owner,Value=Oghenero \